### ISSUE TITLE
Add option to set tile margin around entity

### ISSUE THREAD

**Issue by ajklotz** [raiguard/BlueprintTools#15]
### Description

I've been making wall defense blueprints and I like to use the set tiles feature to add landfill underneath my entities in case of water. When I make a blueprint and use Set Tiles feature, it will place landfill in a big box and I have to go into the blueprint and remove all the extra landfill, or do some magic in editor extensions to get rid of all the extra tiles. See below 

![image](https://user-images.githubusercontent.com/9448682/222809299-e60ec1f9-103e-40f6-a42e-78c16df5be31.png)

Instead, it would be nice to have a setting that lets me set the margin around entities so that it will only fill tiles around nearby entities to make it end up looking like this:
![image](https://user-images.githubusercontent.com/9448682/222809475-7c023a0d-5677-4b28-af3f-d518e612de2f.png)

**Comment by raiguard** [comment]
The set tiles window already supports this - you can uncheck "fill gaps" and adjust the margin as you wish.

![image](https://user-images.githubusercontent.com/3515394/223614090-48d26f82-8a1c-4126-92a2-fd7bcf33b03a.png)
![image](https://user-images.githubusercontent.com/3515394/223614022-864da50b-262f-40b0-9520-ce3f3ab07cfa.png)
