### ISSUE TITLE
GUI artifact when only Blueprint Tools uses top left corner shortcuts.

### ISSUE THREAD

**Issue by Ybaedbaenn** [raiguard/BlueprintTools#18]
### Description

When using the latest version of Factorio, Factorio Library, and Blueprint Tools, the mod causes a small empty GUI border to appear in the top left corner of the game:
![image](https://user-images.githubusercontent.com/84321760/230723072-be567c0f-4914-43f5-9d31-f899ee4f2aac.png)
The border becomes normal (bigger and filled with shortcuts) when holding a blueprint, or using other mod that has a shortcut there (like Factory Planner).
[factorio-current.log](https://github.com/raiguard/BlueprintTools/files/11183346/factorio-current.log)

### Reproduction

1. Load a save file with only Blueprint Tools (and the required flib).
2. See the glitch.

**Comment by raiguard** [comment]
There isn't a good solution for this. The game itself adds that border and the isn't a way for it to auto hide when all children are hidden. I could instead disable the buttons when they're not usable instead of hiding them, but that would take up unnecessary space.

**Comment by Ybaedbaenn** [comment]
Thanks for checking the issue.

Can the buttons be instead moved to the blueprints' GUI, to the bottom shortcut bar, or some other place (possibly configured in the mod's settings)?

If no, then I guess the issue can be closed, unless you have an idea for a different workaround.

**Comment by raiguard** [comment]
I could put them in the shortcut bar, but then they would always be visible and would take up even more space in that limited area. Putting them in the blueprint GUI would make them much less convenient to use.
