### ISSUE TITLE
blueprint tools in side bar

### ISSUE THREAD

**Issue by Alkumist** [raiguard/BlueprintTools#19]
could the blueprint tool buttons also be in the new blueprint library side bar this mod adds?
![Screenshot 2023-05-19 002535](https://github.com/raiguard/BlueprintTools/assets/23058281/e8207a6a-0988-45b6-ae5f-fc36eb0b811f)

**Comment by raiguard** [comment]
The problems there are that you need to be holding a blueprint for the buttons to work, and the buttons don't work with blueprints in the library. The latter is a fundamental API limitation that can't be overcome by mods (yet).
