### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by ZwerOxotnik** [raiguard/BlueprintTools#20]
I'd like to use some stuff from https://github.com/raiguard/BlueprintTools/blob/master/scripts/util.lua in the future, but I didn't find it in https://github.com/raiguard/Factorio-RaiLuaLib/tree/master nor in https://github.com/factoriolib/flib, although I'd use it as static library even. Is there any library with the stuff?

**Comment by raiguard** [comment]
This mod is due for a refactor, so when I do that I'll see which functions I can move into flib.

**Comment by raiguard** [comment]
I'm closing this, but it's still on the plan for flib.
